repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: nbqa-isort
        name: Run isort
        entry: poetry run nbqa isort notebooks
        language: system
      - id: nbqa-black
        name: Run black
        entry: poetry run nbqa black notebooks
        language: system
